# todo-backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: app
        image: inosha1/todo-backend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: todo-backend-config
        - secretRef:
            name: todo-backend-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret
  namespace: project
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  DB_USER: todouser
  DB_NAME: tododb
  DB_HOST: todo-db
  DB_PORT: "5432"
  PORT: "4000"

