apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picsum-pvc # 
  namespace: project
spec:
  storageClassName: picsum-pv # 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi