apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-cron
  namespace: project
spec:
  schedule: "0 * * * *" 
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: random-todo
            image: inosha1/random-todo-cron:v1
            imagePullPolicy: Always
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:2345/todos"
