apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: inosha1/log_output_app:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: PING_URL
              value: "http://ping-pong-app-svc:2345/pings"
