apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: inosha1/ping-pong:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: PGHOST
              value: "postgres.exercises.svc.cluster.local"   # namespace 'exercises'
            - name: PGPORT
              value: "5432"

---
# LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
  namespace: exercises
spec:
  type: LoadBalancer
  selector:  
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000