apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ping-pong-ing
  namespace: exercises

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-app-svc
            port:
              number: 80
      - path: /pings
        pathType: Prefix
        backend:
          service:
            name: ping-pong-app-svc
            port:
              number: 80
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-app-svc
            port:
              number: 80
# PGPASSWORD=pingpong psql -h postgres.exercises.svc.cluster.local -U pingpong -d pingpong