apiVersion: v1
kind: Service
metadata:
  name: log-output-app-svc
spec:
  selector:
    app: log-output-app
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
spec:
  selector:
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 3000
