apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  selector:
    app: pingpong
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 3001
