apiVersion: v1
kind: Service
metadata:
  name: log-output-app-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
